#!/usr/bin/env python3
# -*- mode: python; coding: utf-8 -*-
#
# Copyright 2013 Andrej Antonov <polymorphm@gmail.com>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

assert str is not bytes

import argparse, sys, os, random, itertools, datetime

DATA_PART_SIZE = 1000000
DATA_PART_UI_SUFFIX = 'MB'
RANDOM_PART_COUNT = 100
WORSE_LIST_COUNT = 20

def new_data_gen():
    # create generator of random data
    
    first_part = bytes(DATA_PART_SIZE)
    part_list = tuple(os.urandom(DATA_PART_SIZE) for part_i in range(RANDOM_PART_COUNT))
    
    def data_gen():
        yield first_part
        
        while True:
            yield random.choice(part_list)
    
    return data_gen()

def new_zero_data_gen():
    # create generator of zero data
    
    part = bytes(DATA_PART_SIZE)
    
    def zero_data_gen():
        while True:
            yield part
    
    return zero_data_gen()

def show_result(work_time_list, n):
    assert n >= 1
    
    if n == 1:
        averaged_work_time_list = work_time_list
    else:
        averaged_work_time_list = []
        work_time_list_iter = iter(work_time_list)
        
        while True:
            work_time_slice = tuple(itertools.islice(work_time_list_iter, n))
            if len(work_time_slice) < n:
                break
            
            averaged_work_time = None
            for work_time in work_time_slice:
                if averaged_work_time is None:
                    averaged_work_time = work_time
                    
                    continue
                
                averaged_work_time += work_time
            
            averaged_work_time_list.append(averaged_work_time)
    
    if not averaged_work_time_list:
        return
    
    worse_time_per_n_list = tuple(reversed(sorted(averaged_work_time_list)))[:WORSE_LIST_COUNT]
    
    print('worse time per {!r}{}:'.format(n, DATA_PART_UI_SUFFIX))
    
    for work_time in worse_time_per_n_list:
        print('{!r} days {!r} seconds {!r} microseconds'.format(
                    work_time.days,
                    work_time.seconds,
                    work_time.microseconds,
                    ))

def main():
    parser = argparse.ArgumentParser(
            description='utility for speed measuring of file reading or writing',
            )
    
    parser.add_argument(
            '--verbose',
            action='store_true',
            help='show speed measuring of each iteration',
            )
    
    parser.add_argument(
            '--read-test',
            action='store_true',
            help='use read file test type',
            )
    
    parser.add_argument(
            '--write-test',
            action='store_true',
            help='use write file test type',
            )
    
    parser.add_argument(
            '--file',
            metavar='PATH',
            help='path to file for read/write operations',
            )
    
    parser.add_argument(
            '--size',
            metavar='SIZE',
            type=int,
            help='size (in megabytes) for read/write',
            )
    
    parser.add_argument(
            '--fake',
            action='store_true',
            help='use fake mode: not perform any read/write operations',
            )
    
    parser.add_argument(
            '--zero',
            action='store_true',
            help='generate zero data instead of random data (for write operations)',
            )
    
    parser.add_argument(
            '--not-flush',
            action='store_true',
            help='not use flush (for write operations)',
            )
    
    args = parser.parse_args()
    
    if not args.read_test and not args.write_test:
        print('argument error: no test type', file=sys.stderr)
        exit(2)
    
    if args.read_test and args.write_test:
        print('argument error: test type conflict', file=sys.stderr)
        exit(2)
    
    if not args.file and not args.fake:
        print('argument error: no file', file=sys.stderr)
        exit(2)
    
    if (args.write_test or args.fake) and (not args.size or args.size < 0):
        print('argument error: no size', file=sys.stderr)
        exit(2)
    
    if args.write_test:
        print('preparing data...')
        
        if not args.zero:
            data_gen = new_data_gen()
        else:
            data_gen = new_zero_data_gen()
        
        print('preparing data: done')
    else:
        data_gen = None
    
    if args.fake:
        fd = None
    elif args.read_test:
        fd = open(args.file, mode='rb')
    elif args.write_test:
        fd = open(args.file, mode='wb')
    else:
        assert False
    
    class IterCtx:
        pass
    
    iter_ctx = IterCtx()
    
    if args.read_test:
        def pre_iteration():
            pass
        
        def iteration():
            if args.fake:
                return
            
            assert fd is not None
            read_data = fd.read(DATA_PART_SIZE)
            
            if not read_data:
                raise StopIteration
    elif args.write_test:
        def pre_iteration():
            assert data_gen is not None
            iter_ctx.data = next(data_gen)
        
        def iteration():
            if args.fake:
                return
            
            assert fd is not None
            fd.write(iter_ctx.data)
            if not args.not_flush:
                fd.flush()
    else:
        assert False
    
    print('testing...')
    
    work_time_list = []
    
    def iteration_range(size):
        if size is not None:
            yield from range(size)
        else:
            yield from itertools.count()
    
    for iteration_i in iteration_range(args.size):
        pre_iteration()
        
        begin_time = datetime.datetime.now()
        try:
            iteration()
        except StopIteration:
            break
        end_time = datetime.datetime.now()
        work_time = end_time - begin_time
        work_time_list.append(work_time)
        
        if args.verbose:
            print('[{!r}] done test iteration: {!r} days {!r} seconds {!r} microseconds'.format(
                    iteration_i,
                    work_time.days,
                    work_time.seconds,
                    work_time.microseconds,
                    ))
    
    work_time_list = tuple(work_time_list)
    
    print('testing: done')
    
    if fd is not None:
        fd.close()
    
    n = 1
    while n < len(work_time_list):
        show_result(work_time_list, n)
        n *= 10

if __name__ == '__main__':
    main()
